#!/usr/bin/env bash
# Interactive wizard that creates config/cluster.env from cluster.example.env.
# Prompts for the smallest viable set of customer-specific values; everything
# else uses the example defaults and can be edited later in cluster.env.
#
# Usage:
#   scripts/init-config.sh           # interactive, refuses to overwrite
#   scripts/init-config.sh --force   # interactive, overwrites cluster.env
#   YES=1 scripts/init-config.sh     # non-interactive, only valid with --force
#                                    # when cluster.env already exists
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXAMPLE="$REPO_ROOT/config/cluster.example.env"
TARGET="$REPO_ROOT/config/cluster.env"

FORCE=0
for arg in "$@"; do
  case "$arg" in
    --force|-f) FORCE=1 ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

[[ -f "$EXAMPLE" ]] || { echo "missing $EXAMPLE" >&2; exit 1; }

if [[ -f "$TARGET" && "$FORCE" -ne 1 ]]; then
  echo "config/cluster.env already exists. Rerun with --force to overwrite." >&2
  exit 1
fi

ask() {
  # ask VAR_NAME "Prompt text" "default value"
  local var="$1" prompt="$2" default="${3:-}"
  local val
  if [[ "${YES:-0}" == "1" ]]; then
    val="$default"
  else
    if [[ -n "$default" ]]; then
      read -r -p "$prompt [$default]: " val || true
    else
      read -r -p "$prompt: " val || true
    fi
    val="${val:-$default}"
  fi
  printf -v "$var" '%s' "$val"
}

echo "ocp-multus init-config wizard"
echo "Press Enter to accept the default shown in brackets."
echo

ask CLUSTER_NAME             "Cluster name (lowercase alphanumeric, <=15 chars)" "lab"
ask LOCATION                 "Azure region"                                       "swedencentral"
ask ARCHITECTURE             "Cluster CPU architecture (x86_64 or arm64)"         "x86_64"
ask CLUSTER_SUBSCRIPTION_ID  "Subscription ID where the cluster is deployed"      ""
ask DNS_SUBSCRIPTION_ID      "Subscription ID where the parent DNS zone lives"    "$CLUSTER_SUBSCRIPTION_ID"
ask PARENT_DNS_ZONE          "Parent public DNS zone (e.g. example.com)"          ""
ask PARENT_DNS_RESOURCE_GROUP "Resource group of the parent DNS zone"             ""
ask BASE_DOMAIN              "Cluster sub-zone (e.g. ocp.\$PARENT_DNS_ZONE)"      "ocp.$PARENT_DNS_ZONE"
ask WORKLOAD_RESOURCE_GROUP  "Cluster workload resource group (will be created)"  "rg-${CLUSTER_NAME}-ocp"
ask NETWORK_RESOURCE_GROUP   "Resource group containing the cluster VNet"         "rg-${CLUSTER_NAME}-net"
ask VIRTUAL_NETWORK          "VNet name (must already exist)"                     "vnet-${CLUSTER_NAME}-ocp"
ask MACHINE_NETWORK_CIDR     "Spoke VNet machine CIDR (covers all OS subnets)"    "10.20.0.0/22"
ask ADMIN_SSH_SOURCE_IP      "Admin SSH source CIDR (your workstation /32)"       ""
ask DNS_RESOURCE_GROUP       "Resource group of the parent DNS zone (legacy)"     "$PARENT_DNS_RESOURCE_GROUP"
ask HUB_DNS_RESOURCE_GROUP   "RG holding privatelink.blob.core.windows.net zone"  "$NETWORK_RESOURCE_GROUP"

if [[ -z "$ADMIN_SSH_SOURCE_IP" ]]; then
  echo "ADMIN_SSH_SOURCE_IP is required. Use your workstation public IP as /32, or your corporate VPN exit CIDR." >&2
  exit 1
fi

if [[ "$ADMIN_SSH_SOURCE_IP" == "0.0.0.0/0" && "${ALLOW_OPEN_SSH:-0}" != "1" ]]; then
  echo "Refusing ADMIN_SSH_SOURCE_IP=0.0.0.0/0 because it opens SSH to the internet." >&2
  echo "Use a /32 or VPN CIDR, or set ALLOW_OPEN_SSH=1 if this is a throwaway lab." >&2
  exit 1
fi

# Subnets — start from the example template; the wizard does not prompt for
# the per-subnet CIDRs unless the user opted in to advanced editing. They
# can be tuned later by editing config/cluster.env.

PULL_SECRET_FILE="secrets/pull-secret.txt"
SSH_PUBLIC_KEY_FILE="secrets/id_ed25519.pub"

cat > "$TARGET" <<EOF
# Generated by scripts/init-config.sh on $(date -u +%FT%TZ).
# Edit this file directly to tune values; re-run 'make tfvars' to propagate
# changes into the Terraform stacks.

CLUSTER_NAME=$CLUSTER_NAME
BASE_DOMAIN=$BASE_DOMAIN
LOCATION=$LOCATION
ARCHITECTURE=$ARCHITECTURE

CLUSTER_SUBSCRIPTION_ID=$CLUSTER_SUBSCRIPTION_ID
DNS_SUBSCRIPTION_ID=$DNS_SUBSCRIPTION_ID
PRIVATE_DNS_SUBSCRIPTION_ID=$CLUSTER_SUBSCRIPTION_ID

DNS_RESOURCE_GROUP=$DNS_RESOURCE_GROUP
NETWORK_RESOURCE_GROUP=$NETWORK_RESOURCE_GROUP
WORKLOAD_RESOURCE_GROUP=$WORKLOAD_RESOURCE_GROUP
VIRTUAL_NETWORK=$VIRTUAL_NETWORK

PARENT_DNS_ZONE=$PARENT_DNS_ZONE
PARENT_DNS_RESOURCE_GROUP=$PARENT_DNS_RESOURCE_GROUP
HUB_DNS_RESOURCE_GROUP=$HUB_DNS_RESOURCE_GROUP

ADMIN_SSH_SOURCE_IP=$ADMIN_SSH_SOURCE_IP
CREATE_WINDOWS_JUMP=false

INFRA_ID=

CONTROL_PLANE_SUBNET=snet-ocp-master
COMPUTE_SUBNET=snet-ocp-worker

# Subnet CIDRs (defaults sized for a small PoC; resize before production).
SUBNET_MASTER_CIDR=10.20.1.0/28
SUBNET_WORKER_CIDR=10.20.1.16/28
SUBNET_BOOTSTRAP_CIDR=10.20.1.32/28
SUBNET_MULTUS_CIDR=10.20.2.0/24
SUBNET_SRIOV_CIDR=10.20.3.0/24

MACHINE_NETWORK_CIDR=$MACHINE_NETWORK_CIDR
CLUSTER_NETWORK_CIDR=10.128.0.0/14
CLUSTER_NETWORK_HOST_PREFIX=23
SERVICE_NETWORK_CIDR=172.30.0.0/16

CONTROL_PLANE_VM_SIZE=Standard_D8s_v5
WORKER_VM_SIZE=Standard_D4s_v5
SRIOV_WORKER_VM_SIZE=Standard_D8s_v5

PULL_SECRET_FILE=$PULL_SECRET_FILE
SSH_PUBLIC_KEY_FILE=$SSH_PUBLIC_KEY_FILE

# Cluster topology — defaults match install-config/install-config.yaml.tmpl.
PUBLISH=Internal
EOF

chmod 600 "$TARGET"

echo
echo "Wrote $TARGET (mode 600)."
echo "Next steps:"
echo "  1. cp secrets/pull-secret.example.txt secrets/pull-secret.txt   # paste your Red Hat pull secret"
echo "  2. ssh-keygen -t ed25519 -f secrets/id_ed25519 -N ''            # cluster SSH key"
echo "  3. az login                                                      # set the active subscription"
echo "  4. make tools                                                    # download openshift-install + oc"
echo "  5. make tfvars                                                   # render per-stack tfvars"
echo "  6. make verify                                                   # local sanity check"
echo "  7. make all                                                      # one-command install (~60 min)"
