#!/usr/bin/env bash
# Render *.auto.tfvars files into each terraform stack from config/cluster.env
# so that ARCHITECTURE and VM sizes set in cluster.env are the single source of
# truth — even for Terraform. The generated files are gitignored.
#
# Wired into the Makefile: every `make network|image|bootstrap|control-plane|
# workers` target depends on `tfvars` and runs this script first.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="${CONFIG_FILE:-$REPO_ROOT/config/cluster.env}"

[[ -f "$CONFIG_FILE" ]] || { echo "missing $CONFIG_FILE (copy config/cluster.example.env first)" >&2; exit 1; }

set -a
# shellcheck source=/dev/null
source "$CONFIG_FILE"
set +a

: "${ARCHITECTURE:?ARCHITECTURE not set in $CONFIG_FILE (expected: x86_64 | arm64)}"
case "$ARCHITECTURE" in
  x86_64|arm64) ;;
  *)
    echo "Unsupported ARCHITECTURE='$ARCHITECTURE' (expected: x86_64 | arm64)" >&2
    exit 1
    ;;
esac

: "${CONTROL_PLANE_VM_SIZE:?CONTROL_PLANE_VM_SIZE not set in $CONFIG_FILE}"
: "${WORKER_VM_SIZE:?WORKER_VM_SIZE not set in $CONFIG_FILE}"
SRIOV_WORKER_VM_SIZE="${SRIOV_WORKER_VM_SIZE:-$CONTROL_PLANE_VM_SIZE}"

write_tfvars() {
  local target="$1"
  local body="$2"
  mkdir -p "$(dirname "$target")"
  printf '# Generated by scripts/render-tfvars.sh from config/cluster.env. Do not edit by hand.\n%s\n' "$body" > "$target"
  echo "Wrote $target"
}

write_tfvars "$REPO_ROOT/terraform/01-network/architecture.auto.tfvars" "architecture = \"$ARCHITECTURE\""
write_tfvars "$REPO_ROOT/terraform/02-image/architecture.auto.tfvars"   "architecture = \"$ARCHITECTURE\""
write_tfvars "$REPO_ROOT/terraform/03-bootstrap/vm-size.auto.tfvars"    "vm_size = \"$WORKER_VM_SIZE\""
write_tfvars "$REPO_ROOT/terraform/04-control-plane/vm-size.auto.tfvars" "vm_size = \"$CONTROL_PLANE_VM_SIZE\""
write_tfvars "$REPO_ROOT/terraform/05-workers/vm-size.auto.tfvars" "$(printf 'vm_size              = "%s"\nsriov_worker_vm_size = "%s"' "$WORKER_VM_SIZE" "$SRIOV_WORKER_VM_SIZE")"
